### ISSUE TITLE
Inventories endpoint is not returning warehouse name

### ISSUE THREAD

**Issue by zahrafalak** [ryn-ngn/instock-group-2-server#10]
The requirement to return the warehouse name was not fulfilled for this backend ticket. 

<img width="646" alt="Screenshot 2024-03-21 at 7 07 31 PM" src="https://github.com/ryn-ngn/instock-group-2-server/assets/143557661/e375ef28-3501-413c-8c01-b30d572b4024">

**Comment by Elizabeth-Sorescu** [comment]
Thank you for pointing this out, Falak. Should I make changes on the same branch? or create a new branch and create a PR request?
